export const bandeiras = [
    { pais: "Andorra", imagem: "./assets/svg/ad.svg" },
   { pais: "Emirados Árabes Unidos", imagem: "./assets/svg/ae.svg" },
   { pais: "Afeganistão", imagem: "./assets/svg/af.svg" },
   { pais: "Antígua e Barbuda", imagem: "./assets/svg/ag.svg" },
   { pais: "Anguilla", imagem: "./assets/svg/ai.svg" },
   { pais: "Albânia", imagem: "./assets/svg/al.svg" },
   { pais: "Armênia", imagem: "./assets/svg/am.svg" },
   { pais: "Angola", imagem: "./assets/svg/ao.svg" },
   { pais: "Antártida", imagem: "./assets/svg/aq.svg" },
   { pais: "Argentina", imagem: "./assets/svg/ar.svg" },
   { pais: "Arábia Saudita", imagem: "./assets/svg/arab.svg" },
   { pais: "Samoa Americana", imagem: "./assets/svg/as.svg" },
   { pais: "ASEAN", imagem: "./assets/svg/asean.svg" },
   { pais: "Áustria", imagem: "./assets/svg/at.svg" },
   { pais: "Austrália", imagem: "./assets/svg/au.svg" },
   { pais: "Aruba", imagem: "./assets/svg/aw.svg" },
   { pais: "Ilhas Åland", imagem: "./assets/svg/ax.svg" },
   { pais: "Azerbaijão", imagem: "./assets/svg/az.svg" },
   { pais: "Bósnia e Herzegovina", imagem: "./assets/svg/ba.svg" },
   { pais: "Barbados", imagem: "./assets/svg/bb.svg" },
   { pais: "Bangladesh", imagem: "./assets/svg/bd.svg" },
   { pais: "Bélgica", imagem: "./assets/svg/be.svg" },
   { pais: "Burkina Faso", imagem: "./assets/svg/bf.svg" },
   { pais: "Bulgária", imagem: "./assets/svg/bg.svg" },
   { pais: "Bahrein", imagem: "./assets/svg/bh.svg" },
   { pais: "Burundi", imagem: "./assets/svg/bi.svg" },
   { pais: "Benin", imagem: "./assets/svg/bj.svg" },
  //  { pais: "São Bartolomeu", imagem: "./assets/svg/bl.svg" },
   { pais: "Bermudas", imagem: "./assets/svg/bm.svg" },
   { pais: "Brunei", imagem: "./assets/svg/bn.svg" },
   { pais: "Bolívia", imagem: "./assets/svg/bo.svg" },
  //  { pais: "Países Baixos Caribenhos", imagem: "./assets/svg/bq.svg" },
   { pais: "Brasil", imagem: "./assets/svg/br.svg" },
   { pais: "Bahamas", imagem: "./assets/svg/bs.svg" },
   { pais: "Butão", imagem: "./assets/svg/bt.svg" },
   { pais: "Ilha Bouvet", imagem: "./assets/svg/bv.svg" },
   { pais: "Botsuana", imagem: "./assets/svg/bw.svg" },
   { pais: "Bielorrússia", imagem: "./assets/svg/by.svg" },
   { pais: "Belize", imagem: "./assets/svg/bz.svg" },
   { pais: "Canadá", imagem: "./assets/svg/ca.svg" },
   { pais: "Ilhas Cocos", imagem: "./assets/svg/cc.svg" },
   { pais: "República Democrática do Congo", imagem: "./assets/svg/cd.svg" },
   { pais: "CEFTA", imagem: "./assets/svg/cefta.svg" },
   { pais: "República Centro-Africana", imagem: "./assets/svg/cf.svg" },
   { pais: "Congo", imagem: "./assets/svg/cg.svg" },
   { pais: "Suíça", imagem: "./assets/svg/ch.svg" },
   { pais: "Costa do Marfim", imagem: "./assets/svg/ci.svg" },
   { pais: "Ilhas Cook", imagem: "./assets/svg/ck.svg" },
   { pais: "Chile", imagem: "./assets/svg/cl.svg" },
   { pais: "Camarões", imagem: "./assets/svg/cm.svg" },
   { pais: "China", imagem: "./assets/svg/cn.svg" },
   { pais: "Colômbia", imagem: "./assets/svg/co.svg" },
   { pais: "Ilha Clipperton", imagem: "./assets/svg/cp.svg" },
   { pais: "Costa Rica", imagem: "./assets/svg/cr.svg" },
   { pais: "Cuba", imagem: "./assets/svg/cu.svg" },
   { pais: "Cabo Verde", imagem: "./assets/svg/cv.svg" },
   { pais: "Curaçao", imagem: "./assets/svg/cw.svg" },
   { pais: "Ilha Christmas", imagem: "./assets/svg/cx.svg" },
   { pais: "Chipre", imagem: "./assets/svg/cy.svg" },
   { pais: "República Tcheca", imagem: "./assets/svg/cz.svg" },
   { pais: "Alemanha", imagem: "./assets/svg/de.svg" },
   { pais: "Território Britânico do Oceano Índico", imagem: "./assets/svg/dg.svg" },
   { pais: "Djibouti", imagem: "./assets/svg/dj.svg" },
   { pais: "Dinamarca", imagem: "./assets/svg/dk.svg" },
   { pais: "Dominica", imagem: "./assets/svg/dm.svg" },
   { pais: "República Dominicana", imagem: "./assets/svg/do.svg" },
   { pais: "Argélia", imagem: "./assets/svg/dz.svg" },
   { pais: "Comunidade da África Oriental", imagem: "./assets/svg/eac.svg" },
   { pais: "Equador", imagem: "./assets/svg/ec.svg" },
   { pais: "Estônia", imagem: "./assets/svg/ee.svg" },
   { pais: "Egito", imagem: "./assets/svg/eg.svg" },
   { pais: "Saara Ocidental", imagem: "./assets/svg/eh.svg" },
   { pais: "Eritreia", imagem: "./assets/svg/er.svg" },
   { pais: "Espanha", imagem: "./assets/svg/es.svg" },
   { pais: "Etiópia", imagem: "./assets/svg/et.svg" },
   { pais: "União Europeia", imagem: "./assets/svg/eu.svg" },
   { pais: "Finlândia", imagem: "./assets/svg/fi.svg" },
   { pais: "Fiji", imagem: "./assets/svg/fj.svg" },
   { pais: "Ilhas Malvinas", imagem: "./assets/svg/fk.svg" },
   { pais: "Micronésia", imagem: "./assets/svg/fm.svg" },
   { pais: "Ilhas Faroe", imagem: "./assets/svg/fo.svg" },
   { pais: "França", imagem: "./assets/svg/fr.svg" },
   { pais: "Gabão", imagem: "./assets/svg/ga.svg" },
   { pais: "Reino Unido", imagem: "./assets/svg/gb.svg" },
   { pais: "Granada", imagem: "./assets/svg/gd.svg" },
   { pais: "Geórgia", imagem: "./assets/svg/ge.svg" },
  //  { pais: "Guiana Francesa", imagem: "./assets/svg/gf.svg" },
   { pais: "Guernsey", imagem: "./assets/svg/gg.svg" },
   { pais: "Gana", imagem: "./assets/svg/gh.svg" },
   { pais: "Gibraltar", imagem: "./assets/svg/gi.svg" },
   { pais: "Groenlândia", imagem: "./assets/svg/gl.svg" },
   { pais: "Gâmbia", imagem: "./assets/svg/gm.svg" },
   { pais: "Guiné", imagem: "./assets/svg/gn.svg" },
   { pais: "Guadalupe", imagem: "./assets/svg/gp.svg" },
   { pais: "Guiné Equatorial", imagem: "./assets/svg/gq.svg" },
   { pais: "Grécia", imagem: "./assets/svg/gr.svg" },
   { pais: "Ilhas Geórgia do Sul e Sandwich do Sul", imagem: "./assets/svg/gs.svg" },
   { pais: "Guatemala", imagem: "./assets/svg/gt.svg" },
   { pais: "Guam", imagem: "./assets/svg/gu.svg" },
   { pais: "Guiné-Bissau", imagem: "./assets/svg/gw.svg" },
   { pais: "Guiana", imagem: "./assets/svg/gy.svg" },
   { pais: "Hong Kong", imagem: "./assets/svg/hk.svg" },
  //  { pais: "Ilhas Heard e McDonald", imagem: "./assets/svg/hm.svg" },
   { pais: "Honduras", imagem: "./assets/svg/hn.svg" },
   { pais: "Croácia", imagem: "./assets/svg/hr.svg" },
   { pais: "Haiti", imagem: "./assets/svg/ht.svg" },
   { pais: "Hungria", imagem: "./assets/svg/hu.svg" },
   { pais: "Indonésia", imagem: "./assets/svg/id.svg" },
   { pais: "Irlanda", imagem: "./assets/svg/ie.svg" },
   { pais: "Israel", imagem: "./assets/svg/il.svg" },
   { pais: "Índia", imagem: "./assets/svg/in.svg" },
   { pais: "Iraque", imagem: "./assets/svg/iq.svg" },
   { pais: "Irã", imagem: "./assets/svg/ir.svg" },
   { pais: "Islândia", imagem: "./assets/svg/is.svg" },
   { pais: "Itália", imagem: "./assets/svg/it.svg" },
   { pais: "Jamaica", imagem: "./assets/svg/jm.svg" },
   { pais: "Jordânia", imagem: "./assets/svg/jo.svg" },
   { pais: "Japão", imagem: "./assets/svg/jp.svg" },
   { pais: "Quênia", imagem: "./assets/svg/ke.svg" },
   { pais: "Quirguistão", imagem: "./assets/svg/kg.svg" },
   { pais: "Camboja", imagem: "./assets/svg/kh.svg" },
   { pais: "Kiribati", imagem: "./assets/svg/ki.svg" },
   { pais: "Comores", imagem: "./assets/svg/km.svg" },
   { pais: "São Cristóvão e Névis", imagem: "./assets/svg/kn.svg" },
   { pais: "Coreia do Norte", imagem: "./assets/svg/kp.svg" },
   { pais: "Coreia do Sul", imagem: "./assets/svg/kr.svg" },
   { pais: "Kuwait", imagem: "./assets/svg/kw.svg" },
   { pais: "Cazaquistão", imagem: "./assets/svg/kz.svg" },
   { pais: "Laos", imagem: "./assets/svg/la.svg" },
   { pais: "Líbano", imagem: "./assets/svg/lb.svg" },
   { pais: "Santa Lúcia", imagem: "./assets/svg/lc.svg" },
   { pais: "Liechtenstein", imagem: "./assets/svg/li.svg" },
   { pais: "Sri Lanka", imagem: "./assets/svg/lk.svg" },
   { pais: "Libéria", imagem: "./assets/svg/lr.svg" },
   { pais: "Lesoto", imagem: "./assets/svg/ls.svg" },
   { pais: "Lituânia", imagem: "./assets/svg/lt.svg" },
   { pais: "Luxemburgo", imagem: "./assets/svg/lu.svg" },
   { pais: "Letônia", imagem: "./assets/svg/lv.svg" },
   { pais: "Líbia", imagem: "./assets/svg/ly.svg" },
   { pais: "Marrocos", imagem: "./assets/svg/ma.svg" },
   { pais: "Mônaco", imagem: "./assets/svg/mc.svg" },
   { pais: "Moldávia", imagem: "./assets/svg/md.svg" },
   { pais: "Montenegro", imagem: "./assets/svg/me.svg" },
   { pais: "Madagascar", imagem: "./assets/svg/mg.svg" },
   { pais: "Ilhas Marshall", imagem: "./assets/svg/mh.svg" },
   { pais: "Macedônia do Norte", imagem: "./assets/svg/mk.svg" },
   { pais: "Mali", imagem: "./assets/svg/ml.svg" },
   { pais: "Mianmar", imagem: "./assets/svg/mm.svg" },
   { pais: "Mongólia", imagem: "./assets/svg/mn.svg" },
   { pais: "Macau", imagem: "./assets/svg/mo.svg" },
   { pais: "Ilhas Marianas do Norte", imagem: "./assets/svg/mp.svg" },
   { pais: "Martinica", imagem: "./assets/svg/mq.svg" },
   { pais: "Mauritânia", imagem: "./assets/svg/mr.svg" },
   { pais: "Montserrat", imagem: "./assets/svg/ms.svg" },
   { pais: "Malta", imagem: "./assets/svg/mt.svg" },
   { pais: "Maurício", imagem: "./assets/svg/mu.svg" },
   { pais: "Maldivas", imagem: "./assets/svg/mv.svg" },
   { pais: "Malawi", imagem: "./assets/svg/mw.svg" },
   { pais: "México", imagem: "./assets/svg/mx.svg" },
   { pais: "Malásia", imagem: "./assets/svg/my.svg" },
   { pais: "Moçambique", imagem: "./assets/svg/mz.svg" },
   { pais: "Namíbia", imagem: "./assets/svg/na.svg" },
   { pais: "Nova Caledônia", imagem: "./assets/svg/nc.svg" },
   { pais: "Níger", imagem: "./assets/svg/ne.svg" },
   { pais: "Ilha Norfolk", imagem: "./assets/svg/nf.svg" },
   { pais: "Nigéria", imagem: "./assets/svg/ng.svg" },
   { pais: "Nicarágua", imagem: "./assets/svg/ni.svg" },
   { pais: "Holanda", imagem: "./assets/svg/nl.svg" },
   { pais: "Noruega", imagem: "./assets/svg/no.svg" },
   { pais: "Nepal", imagem: "./assets/svg/np.svg" },
   { pais: "Nauru", imagem: "./assets/svg/nr.svg" },
   { pais: "Niue", imagem: "./assets/svg/nu.svg" },
   { pais: "Nova Zelândia", imagem: "./assets/svg/nz.svg" },
   { pais: "Omã", imagem: "./assets/svg/om.svg" },
   { pais: "Panamá", imagem: "./assets/svg/pa.svg" },
   { pais: "Peru", imagem: "./assets/svg/pe.svg" },
   { pais: "Polinésia Francesa", imagem: "./assets/svg/pf.svg" },
   { pais: "Papua-Nova Guiné", imagem: "./assets/svg/pg.svg" },
   { pais: "Filipinas", imagem: "./assets/svg/ph.svg" },
   { pais: "Paquistão", imagem: "./assets/svg/pk.svg" },
   { pais: "Polônia", imagem: "./assets/svg/pl.svg" },
  //  { pais: "São Pedro e Miquelão", imagem: "./assets/svg/pm.svg" },
   { pais: "Pitcairn", imagem: "./assets/svg/pn.svg" },
   { pais: "Porto Rico", imagem: "./assets/svg/pr.svg" },
   { pais: "Palestina", imagem: "./assets/svg/ps.svg" },
   { pais: "Portugal", imagem: "./assets/svg/pt.svg" },
   { pais: "Palau", imagem: "./assets/svg/pw.svg" },
   { pais: "Paraguai", imagem: "./assets/svg/py.svg" },
   { pais: "Catar", imagem: "./assets/svg/qa.svg" },
   { pais: "Reunião", imagem: "./assets/svg/re.svg" },
   { pais: "Romênia", imagem: "./assets/svg/ro.svg" },
   { pais: "Sérvia", imagem: "./assets/svg/rs.svg" },
   { pais: "Rússia", imagem: "./assets/svg/ru.svg" },
   { pais: "Ruanda", imagem: "./assets/svg/rw.svg" },
   { pais: "São Cristóvão e Névis", imagem: "./assets/svg/kn.svg" },
   { pais: "Santa Lúcia", imagem: "./assets/svg/lc.svg" },
   { pais: "São Vicente e Granadinas", imagem: "./assets/svg/vc.svg" },
   { pais: "Samoa", imagem: "./assets/svg/ws.svg" },
   { pais: "San Marino", imagem: "./assets/svg/sm.svg" },
   { pais: "São Tomé e Príncipe", imagem: "./assets/svg/st.svg" },
   { pais: "Arábia Saudita", imagem: "./assets/svg/sa.svg" },
   { pais: "Senegal", imagem: "./assets/svg/sn.svg" },
   { pais: "Seicheles", imagem: "./assets/svg/sc.svg" },
   { pais: "Serra Leoa", imagem: "./assets/svg/sl.svg" },
   { pais: "Singapura", imagem: "./assets/svg/sg.svg" },
   { pais: "Eslováquia", imagem: "./assets/svg/sk.svg" },
   { pais: "Eslovênia", imagem: "./assets/svg/si.svg" },
   { pais: "Ilhas Salomão", imagem: "./assets/svg/sb.svg" },
   { pais: "Somália", imagem: "./assets/svg/so.svg" },
   { pais: "África do Sul", imagem: "./assets/svg/za.svg" },
   { pais: "Sudão do Sul", imagem: "./assets/svg/ss.svg" },
   { pais: "Sudão", imagem: "./assets/svg/sd.svg" },
   { pais: "Suriname", imagem: "./assets/svg/sr.svg" },
   { pais: "Suécia", imagem: "./assets/svg/se.svg" },
  //  { pais: "Singapura", imagem: "./assets/svg/sg.svg" },
//  { pais: "Santa Helena", imagem: "./assets/svg/sh.svg" },
 { pais: "Eslovênia", imagem: "./assets/svg/si.svg" },
 { pais: "Svalbard e Jan Mayen", imagem: "./assets/svg/sj.svg" },
 { pais: "Eslováquia", imagem: "./assets/svg/sk.svg" },
 { pais: "Serra Leoa", imagem: "./assets/svg/sl.svg" },
 { pais: "San Marino", imagem: "./assets/svg/sm.svg" },
 { pais: "Senegal", imagem: "./assets/svg/sn.svg" },
 { pais: "Somália", imagem: "./assets/svg/so.svg" },
 { pais: "Suriname", imagem: "./assets/svg/sr.svg" },
 { pais: "Sudão do Sul", imagem: "./assets/svg/ss.svg" },
 { pais: "São Tomé e Príncipe", imagem: "./assets/svg/st.svg" },
 { pais: "El Salvador", imagem: "./assets/svg/sv.svg" },
 { pais: "São Martinho", imagem: "./assets/svg/sx.svg" },
//  { pais: "Síria", imagem: "./assets/svg/sy.svg" },
 { pais: "Essuatíni", imagem: "./assets/svg/sz.svg" },
 { pais: "Ilhas Turcas e Caicos", imagem: "./assets/svg/tc.svg" },
 { pais: "Chade", imagem: "./assets/svg/td.svg" },
 { pais: "Territórios Franceses do Sul", imagem: "./assets/svg/tf.svg" },
 { pais: "Togo", imagem: "./assets/svg/tg.svg" },
 { pais: "Tailândia", imagem: "./assets/svg/th.svg" },
 { pais: "Tajiquistão", imagem: "./assets/svg/tj.svg" },
 { pais: "Tokelau", imagem: "./assets/svg/tk.svg" },
 { pais: "Timor-Leste", imagem: "./assets/svg/tl.svg" },
 { pais: "Turcomenistão", imagem: "./assets/svg/tm.svg" },
 { pais: "Tunísia", imagem: "./assets/svg/tn.svg" },
 { pais: "Tonga", imagem: "./assets/svg/to.svg" },
 { pais: "Turquia", imagem: "./assets/svg/tr.svg" },
 { pais: "Trinidad e Tobago", imagem: "./assets/svg/tt.svg" },
 { pais: "Tuvalu", imagem: "./assets/svg/tv.svg" },
 { pais: "Taiwan", imagem: "./assets/svg/tw.svg" },
 { pais: "Tanzânia", imagem: "./assets/svg/tz.svg" },
 { pais: "Ucrânia", imagem: "./assets/svg/ua.svg" },
 { pais: "Uganda", imagem: "./assets/svg/ug.svg" },
//  { pais: "Ilhas Menores Distantes dos EUA", imagem: "./assets/svg/um.svg" },
 { pais: "Nações Unidas", imagem: "./assets/svg/un.svg" },
 { pais: "Estados Unidos", imagem: "./assets/svg/us.svg" },
 { pais: "Uruguai", imagem: "./assets/svg/uy.svg" },
 { pais: "Uzbequistão", imagem: "./assets/svg/uz.svg" },
 { pais: "Vaticano", imagem: "./assets/svg/va.svg" },
 { pais: "São Vicente e Granadinas", imagem: "./assets/svg/vc.svg" },
 { pais: "Venezuela", imagem: "./assets/svg/ve.svg" },
 { pais: "Ilhas Virgens Britânicas", imagem: "./assets/svg/vg.svg" },
 { pais: "Ilhas Virgens Americanas", imagem: "./assets/svg/vi.svg" },
 { pais: "Vietnã", imagem: "./assets/svg/vn.svg" },
 { pais: "Vanuatu", imagem: "./assets/svg/vu.svg" },
//  { pais: "Wallis e Futuna", imagem: "./assets/svg/wf.svg" },
 { pais: "Samoa", imagem: "./assets/svg/ws.svg" },
 { pais: "Kosovo", imagem: "./assets/svg/xk.svg" },
 // { pais: "Desconhecido", imagem: "./assets/svg/xx.svg" },
 { pais: "Iêmen", imagem: "./assets/svg/ye.svg" },
//  { pais: "Mayotte", imagem: "./assets/svg/yt.svg" },
 { pais: "África do Sul", imagem: "./assets/svg/za.svg" },
 { pais: "Zâmbia", imagem: "./assets/svg/zm.svg" },
 { pais: "Zimbábue", imagem: "./assets/svg/zw.svg" }
 ];

//  linha comentadas precisam ser revisadas, o svg está antigo, já possuem outra bandeira
